### ISSUE TITLE
const valueLimit = 1<<31 - 1

### ISSUE THREAD

**Issue by whidbey** [adamzy/cedar-go#1]
this value I change to const valueLimit = 1<<31 - 1 
not const valueLimit = 1<<63- 1

**Comment by whidbey** [comment]
is likely that your valueLimit =1<<64-1 is int64 and can't compile

**Comment by adamzy** [comment]
You are right.  `int` may be 32 bit on some platforms.
I changed `valueLimit` to `1<<31-1` or `1<<63-1` depends on the platforms.
The specific value can be obtained by `cedar.ValueLimit`.
Thanks.

**Comment by whidbey** [comment]
great
