### ISSUE TITLE
将[]byte改成[]int

### ISSUE THREAD

**Issue by eruca** [adamzy/cedar-go#2]
我将key改为[]byte改成[]int
前面好好看了代码，可是这个算法真心不懂，也没有什么资料可以查看。我就硬着头皮，把key全部改为[]int,简单的测试也可以，后来在载入字典后就panic，切片越界，因为没看懂，所有也无法修改代码，能提供帮助或者把包改进可以使用[]int作为key

**Comment by adamzy** [comment]
用 byte 是因为一般的编码都是以 byte 为单位的。

如果想了解 cedar 的算法，你可能需要先了解一下最简单的双数组前缀树，google 一下 `double array trie` 会有很多结果。然后直接去看 cedar 的日本作者的论文。cedar 的算法貌似是在作者的一篇日文论文里，不过他的几篇英文的论文里有提到相关的思路。这样再去看他的C++代码应该就能懂了。

如果你想要用 `[]int` 做为key，可以把 int 转化成 `[]byte`。

**Comment by qujinqiang** [comment]
兄能留个联系方式交流下吗？
我的QQ号是273459197，盼能够跟兄进行交流！！！
